### ISSUE TITLE
unit test won't clean up db after running

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2-codeception#7]
It's same as [this issue](https://github.com/yiisoft/yii2/issues/9522) from framework main repo. seems like here is a better place for it:

I'm using Yii2 module: (note that `cleanup` is enabled) 
```yml
class_name: UnitTester
modules:
    enabled:
        - Yii2:
            part: ORM
    config:
        Yii2:
            cleanup: true
            configFile: '../config/backend/unit.php'
```

working with `haveRecord()` and `seeRecord()` methods:
```php
    public function testWebsiteInsertion()
    {
        $this->tester->haveRecord(
            Website::className(),
            [
                'title' => 'test site',
                'language' => 'fa',
                'subdomain' => 'test',
                'themeId' => 1
            ]
        );

        $this->tester->seeRecord(
            Website::className(),
            ['subdomain' => 'test']
        );
    }
```
It does not clean up db after running! I traced it down to here `Codeception\Module\Yii2::_after()` :
```php
        if ($this->transaction && $this->config['cleanup']) {
            $this->transaction->rollback();
        }
```
The `if` condition is true and transaction does rollback, but inserted rows do not get removed! I even traced Transaction class in framework core and there were no errors. I'm really stuck, did I miss something? are there other configurations?
